# Generated by Django 6.0.5 on 2026-05-09 05:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('vehicle_number_plate', models.CharField(blank=True, max_length=10)),
                ('transaction_type', models.CharField(choices=[('hire', 'Battery Hire'), ('sale', 'Battery Sale'), ('return', 'Battery Return')], max_length=20)),
                ('battery_size', models.CharField(choices=[('35Ah', '35Ah'), ('45Ah', '45Ah'), ('60Ah', '60Ah'), ('75Ah', '75Ah'), ('100Ah', '100Ah'), ('120Ah', '120Ah'), ('150Ah', '150Ah')], max_length=20)),
                ('battery_brand', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hire_duration_days', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('returned', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('served_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='TyreService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('vehicle_number_plate', models.CharField(blank=True, max_length=10)),
                ('service_type', models.CharField(choices=[('pressure', 'Pressure Check'), ('puncture', 'Puncture Fixing'), ('valve', 'Valve Replacement'), ('tyre_sale', 'Tyre Sale')], max_length=20)),
                ('tyre_size', models.CharField(blank=True, choices=[('155/70R13', '155/70R13'), ('165/70R14', '165/70R14'), ('175/65R14', '175/65R14'), ('185/65R15', '185/65R15'), ('195/65R15', '195/65R15'), ('205/55R16', '205/55R16'), ('215/65R16', '215/65R16'), ('225/45R17', '225/45R17'), ('other', 'Other')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('served_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'System Admin'), ('attendant', 'Parking Attendant'), ('tyre_manager', 'Tyre Section Manager'), ('battery_manager', 'Battery Section Manager')], default='attendant', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('personal_car', 'Personal Car'), ('taxi', 'Taxi'), ('coaster', 'Coaster'), ('boda_boda', 'Boda-Boda')], max_length=20)),
                ('number_plate', models.CharField(max_length=10)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_color', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('nin_number', models.CharField(blank=True, max_length=20)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('parked', 'Parked'), ('signed_out', 'Signed Out')], default='parked', max_length=20)),
                ('parking_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('signout_time', models.DateTimeField(blank=True, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=100)),
                ('receiver_phone', models.CharField(blank=True, max_length=15)),
                ('receiver_gender', models.CharField(blank=True, max_length=10)),
                ('receiver_nin', models.CharField(blank=True, max_length=20)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_vehicles', to=settings.AUTH_USER_MODEL)),
                ('signed_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signedout_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-arrival_time'],
            },
        ),
    ]
